"""initial schema

Revision ID: 114f34d6c5dc
Revises: 
Create Date: 2026-07-08 13:19:37.994306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114f34d6c5dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zenodo_user_id', sa.String(), nullable=False),
    sa.Column('zenodo_env', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zenodo_user_id', 'zenodo_env', name='uq_user_zenodo_identity')
    )
    op.create_index(op.f('ix_users_zenodo_user_id'), 'users', ['zenodo_user_id'], unique=False)
    op.create_table('model_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('concept_doi', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('current_title', sa.String(), nullable=False),
    sa.Column('current_summary', sa.Text(), nullable=False),
    sa.Column('model_type', sa.JSON(), nullable=False),
    sa.Column('language', sa.JSON(), nullable=False),
    sa.Column('script', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_records_concept_doi'), 'model_records', ['concept_doi'], unique=False)
    op.create_index(op.f('ix_model_records_slug'), 'model_records', ['slug'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_record_id', sa.Integer(), nullable=False),
    sa.Column('version_doi', sa.String(), nullable=True),
    sa.Column('zenodo_deposition_id', sa.String(), nullable=True),
    sa.Column('card_yaml', sa.Text(), nullable=False),
    sa.Column('card_body_md', sa.Text(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_record_id'], ['model_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_model_records_slug'), table_name='model_records')
    op.drop_index(op.f('ix_model_records_concept_doi'), table_name='model_records')
    op.drop_table('model_records')
    op.drop_index(op.f('ix_users_zenodo_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
